use std::collections::BTreeMap;
use std::path::PathBuf;
use std::sync::Arc;

use async_trait::async_trait;
use pi_domain::contracts::OverrideStore;
use pi_domain::error::DomainError;
use serde::Serialize;

/// One service block of the generated override. Every field is skipped when
/// absent, so a non-public service emits `environment` alone.
#[derive(Serialize, Default)]
struct ServiceOverride {
    #[serde(skip_serializing_if = "Option::is_none")]
    restart: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    ports: Option<Vec<String>>,
    /// A mapping, never a sequence: compose merges mappings key-wise, so the
    /// generated override (last in the file chain) wins over a same-named key
    /// in the project's own compose file. A sequence would append instead.
    #[serde(skip_serializing_if = "Option::is_none")]
    environment: Option<BTreeMap<String, String>>,
}

#[derive(Serialize)]
struct OverrideDoc {
    services: BTreeMap<String, ServiceOverride>,
}

/// Text of the override file (§12.1): the public service's bind address, plus
/// the `RPI_*` runtime environment for every service of the stack.
///
/// The public service also gets `restart: unless-stopped`. pi owns that
/// service's lifecycle, so it must survive a host reboot without manual
/// intervention; without an explicit policy the container inherits Docker's
/// default `no` and stays down until someone runs `docker start`.
/// `unless-stopped` (not `always`) so a deliberate `rpi stop` is respected
/// across reboots.
///
/// `services` comes from compose discovery and may be empty or stale, so the
/// public service is emitted unconditionally — its port mapping is the one
/// thing the deploy cannot work without.
pub(crate) fn override_yaml(
    service: &str,
    bind: &str,
    host_port: u16,
    container_port: u16,
    services: &[String],
    env: &BTreeMap<String, String>,
) -> String {
    let mut doc = OverrideDoc {
        services: BTreeMap::new(),
    };
    let environment = (!env.is_empty()).then(|| env.clone());
    for name in services {
        if name == service {
            continue;
        }
        if environment.is_none() {
            continue;
        }
        doc.services.insert(
            name.clone(),
            ServiceOverride {
                environment: environment.clone(),
                ..Default::default()
            },
        );
    }
    doc.services.insert(
        service.to_string(),
        ServiceOverride {
            restart: Some("unless-stopped".to_string()),
            ports: Some(vec![format!("{bind}:{host_port}:{container_port}")]),
            environment,
        },
    );
    let body = serde_yaml::to_string(&doc).expect("override doc is always serializable");
    format!("# generated by pi - do not edit\n{body}")
}

pub struct FsOverrideStore {
    dir: PathBuf,
}

impl FsOverrideStore {
    pub fn new(dir: PathBuf) -> Arc<FsOverrideStore> {
        Arc::new(FsOverrideStore { dir })
    }
}

#[async_trait]
impl OverrideStore for FsOverrideStore {
    fn path(&self, project: &str) -> PathBuf {
        self.dir.join(format!("{project}.yml"))
    }

    async fn write(
        &self,
        project: &str,
        service: &str,
        bind: &str,
        host_port: u16,
        container_port: u16,
        services: &[String],
        env: &BTreeMap<String, String>,
    ) -> Result<PathBuf, DomainError> {
        let io_err = |e: std::io::Error| DomainError::Storage(format!("override write: {e}"));
        tokio::fs::create_dir_all(&self.dir).await.map_err(io_err)?;
        let path = self.dir.join(format!("{project}.yml"));
        tokio::fs::write(
            &path,
            override_yaml(service, bind, host_port, container_port, services, env),
        )
        .await
        .map_err(io_err)?;
        Ok(path)
    }

    async fn remove(&self, project: &str) -> Result<(), DomainError> {
        let io_err = |e: std::io::Error| DomainError::Storage(format!("override remove: {e}"));
        match tokio::fs::remove_file(self.dir.join(format!("{project}.yml"))).await {
            Ok(()) => Ok(()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(io_err(e)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn env() -> BTreeMap<String, String> {
        [
            ("RPI_BRANCH_NAME".to_string(), "feature/login".to_string()),
            ("RPI_PROJECT".to_string(), "myapp--branch".to_string()),
        ]
        .into_iter()
        .collect()
    }

    /// Parse the emitted YAML rather than string-matching it: the whole point
    /// of the rewrite is that values are escaped by an emitter.
    fn parsed(yaml: &str) -> serde_yaml::Value {
        serde_yaml::from_str(yaml).expect("emitted override must be valid YAML")
    }

    #[test]
    fn public_service_keeps_ports_and_restart_policy() {
        let yaml = override_yaml("web", "127.0.0.1", 8000, 3000, &["web".into()], &env());
        let doc = parsed(&yaml);
        let web = &doc["services"]["web"];
        assert_eq!(web["restart"].as_str(), Some("unless-stopped"));
        assert_eq!(
            web["ports"][0].as_str(),
            Some("127.0.0.1:8000:3000"),
            "got:\n{yaml}"
        );
        assert_eq!(
            web["environment"]["RPI_BRANCH_NAME"].as_str(),
            Some("feature/login")
        );
    }

    #[test]
    fn every_other_service_gets_environment_only() {
        let yaml = override_yaml(
            "web",
            "127.0.0.1",
            8000,
            3000,
            &["web".into(), "worker".into(), "db".into()],
            &env(),
        );
        let doc = parsed(&yaml);
        for name in ["worker", "db"] {
            let svc = &doc["services"][name];
            assert_eq!(
                svc["environment"]["RPI_PROJECT"].as_str(),
                Some("myapp--branch"),
                "{name} must receive the runtime environment"
            );
            assert!(svc["ports"].is_null(), "{name} must not publish ports");
            assert!(
                svc["restart"].is_null(),
                "{name} must not pin a restart policy"
            );
        }
    }

    #[test]
    fn environment_is_a_mapping_so_compose_merges_it_by_key() {
        let yaml = override_yaml("web", "127.0.0.1", 8000, 3000, &["web".into()], &env());
        let doc = parsed(&yaml);
        assert!(
            doc["services"]["web"]["environment"].is_mapping(),
            "a sequence would append instead of overriding: {yaml}"
        );
    }

    #[test]
    fn public_service_is_emitted_even_when_discovery_missed_it() {
        let yaml = override_yaml("web", "127.0.0.1", 8000, 3000, &[], &env());
        let doc = parsed(&yaml);
        assert_eq!(
            doc["services"]["web"]["ports"][0].as_str(),
            Some("127.0.0.1:8000:3000")
        );
    }

    #[test]
    fn empty_environment_emits_no_environment_key() {
        let yaml = override_yaml(
            "web",
            "127.0.0.1",
            8000,
            3000,
            &["web".into(), "worker".into()],
            &BTreeMap::new(),
        );
        let doc = parsed(&yaml);
        assert!(doc["services"]["web"]["environment"].is_null());
        assert!(
            doc["services"]["worker"].is_null(),
            "a service with nothing to say must not appear at all"
        );
    }

    #[test]
    fn values_needing_quoting_survive_a_round_trip() {
        let mut env = BTreeMap::new();
        env.insert(
            "RPI_BRANCH_NAME".to_string(),
            "fix/\"quoted\": #1".to_string(),
        );
        env.insert("RPI_HOST_PORT".to_string(), "8000".to_string());
        let yaml = override_yaml("web", "127.0.0.1", 8000, 3000, &["web".into()], &env);
        let doc = parsed(&yaml);
        assert_eq!(
            doc["services"]["web"]["environment"]["RPI_BRANCH_NAME"].as_str(),
            Some("fix/\"quoted\": #1")
        );
        assert_eq!(
            doc["services"]["web"]["environment"]["RPI_HOST_PORT"].as_str(),
            Some("8000"),
            "a numeric-looking value must stay a string"
        );
    }

    #[test]
    fn the_lan_bind_and_a_keyword_branch_name_stay_strings() {
        // The port mapping is emitted as a plain scalar, so the other bind
        // address `ExposeMode::bind_addr` can return has to round-trip as a
        // string too - it is the one thing a deploy cannot work without.
        // And RPI_BRANCH_NAME now carries a user-supplied branch name, which
        // may well be a YAML boolean keyword.
        let mut env = BTreeMap::new();
        env.insert("RPI_BRANCH_NAME".to_string(), "true".to_string());
        let yaml = override_yaml("web", "0.0.0.0", 8000, 3000, &["web".into()], &env);
        let doc = parsed(&yaml);
        assert_eq!(
            doc["services"]["web"]["ports"][0].as_str(),
            Some("0.0.0.0:8000:3000"),
            "got:\n{yaml}"
        );
        assert_eq!(
            doc["services"]["web"]["environment"]["RPI_BRANCH_NAME"].as_str(),
            Some("true"),
            "a branch named like a boolean must stay a string:\n{yaml}"
        );
    }

    #[test]
    fn generated_marker_comment_is_preserved() {
        let yaml = override_yaml("web", "127.0.0.1", 8000, 3000, &["web".into()], &env());
        assert!(
            yaml.starts_with("# generated by pi - do not edit\n"),
            "got:\n{yaml}"
        );
    }

    #[tokio::test]
    async fn write_creates_file_in_overrides_dir() {
        let dir = tempfile::tempdir().unwrap();
        let store = FsOverrideStore::new(dir.path().join("overrides"));
        let path = store
            .write(
                "rateme",
                "web",
                "127.0.0.1",
                8000,
                3000,
                &["web".into()],
                &env(),
            )
            .await
            .unwrap();
        assert_eq!(path, dir.path().join("overrides").join("rateme.yml"));
        let content = tokio::fs::read_to_string(&path).await.unwrap();
        assert!(content.contains("127.0.0.1:8000:3000"));
    }
}
